global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "R&S Marketplace"
    metrics_path: "/metrics"
    scrape_timeout: 10s
    static_configs:
      - targets: ["host.docker.internal:8000"]
        labels:
          application: "R&S Marketplace"

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
